# src/tic/adapters/renderers/markdown_renderer.py
"""Markdown renderer — uses PublicFinding DTO. mode parameter controls IOC detail."""

from __future__ import annotations

from collections.abc import Iterable
from typing import TextIO

from tic.domain.finding import Finding, OutputMode, Severity
from tic.security.ansi_strip import strip_terminal_controls

_SEVERITY_BADGE = {
    Severity.INFO: "INFO",
    Severity.LOW: "LOW",
    Severity.MEDIUM: "MEDIUM",
    Severity.HIGH: "HIGH",
    Severity.CRITICAL: "CRITICAL",
}

_MD_SPECIAL: tuple[str, ...] = (
    "\\",
    "`",
    "*",
    "_",
    "{",
    "}",
    "[",
    "]",
    "(",
    ")",
    "#",
    "<",
    ">",
    "|",
)


def _md_escape(text: str) -> str:
    cleaned = strip_terminal_controls(text)
    for ch in _MD_SPECIAL:
        cleaned = cleaned.replace(ch, "\\" + ch)
    return cleaned


def render_markdown(
    findings: Iterable[Finding],
    out: TextIO,
    *,
    mode: OutputMode = OutputMode.ANALYST,
    hmac_key: bytes | None = None,
) -> int:
    findings_list = list(findings)
    count = len(findings_list)
    out.write("# Threat Intel Correlator — Findings Report\n\n")
    out.write(f"**Total findings:** {count}\n\n")
    if count == 0:
        out.write("_No findings produced for this sweep._\n")
        return 0
    out.write("## Summary\n\n| Severity | Count |\n|---|---|\n")
    for sev in (Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO):
        n = sum(1 for f in findings_list if f.severity == sev)
        out.write(f"| {_SEVERITY_BADGE[sev]} | {n} |\n")
    out.write("\n## Findings\n\n")
    for idx, f in enumerate(findings_list, start=1):
        pub = f.to_public(mode=mode, hmac_key=hmac_key)
        out.write(f"### {idx}. {_SEVERITY_BADGE[f.severity]} — score {pub.score}\n\n")
        out.write(f"- **IOC type:** `{_md_escape(pub.ioc_type)}`\n")
        out.write(f"- **Value:** `{_md_escape(pub.ioc_value)}`\n")
        out.write(f"- **Source:** {_md_escape(pub.ioc_source)}\n")
        out.write(f"- **Matches:** {pub.match_count}\n")
        if pub.ioc_tags:
            out.write(f"- **Tags:** {', '.join(sorted(_md_escape(t) for t in pub.ioc_tags))}\n")
        out.write(f"- **Finding ID:** `{pub.finding_id}`\n")
        out.write(f"- **Profile hash:** `{pub.profile_hash[:16]}…`\n")
        if pub.enrichments:
            out.write(
                "\n**Enrichment results:**\n\n| Provider | Reputation | Tags |\n|---|---|---|\n"
            )
            for e in pub.enrichments:
                rep = str(e.reputation_score) if e.reputation_score is not None else "—"
                tag_str = ", ".join(_md_escape(t) for t in sorted(e.tags)) or "—"
                out.write(f"| {_md_escape(e.provider)} | {rep} | {tag_str} |\n")
        if pub.ai_narrative is not None:
            # AI narrative is rendered as a named subsection so the
            # disclaimer is unmissable in the exported report. The
            # advisory framing matches the threat model: AI never
            # changes score / severity / above_threshold, and the
            # narrative is for analyst triage only.
            out.write("\n#### AI Narrative\n\n")
            out.write(
                "> ⚠ **Advisory only — review required.** "
                "This narrative is generated by an AI model. It does "
                "**not** alter score, severity, or any deterministic "
                "finding field. An analyst MUST verify before acting.\n>\n"
            )
            out.write(f"> {_md_escape(pub.ai_narrative.summary)}\n>\n")
            out.write(f"> _FP likelihood:_ {pub.ai_narrative.false_positive_likelihood} · ")
            out.write(f"_AI confidence:_ {pub.ai_narrative.confidence} · ")
            out.write(f"_Model:_ `{_md_escape(pub.ai_narrative.model)}`\n")
            if pub.ai_narrative.suggested_actions:
                out.write(">\n> **Suggested actions (advisory):**\n")
                for action in pub.ai_narrative.suggested_actions:
                    out.write(f"> - {_md_escape(action)}\n")
            # Backward-compatible string for existing tests asserting the
            # phrase "AI-generated advisory" is present in the export.
            out.write("\n<!-- AI-generated advisory (review required) -->\n")
        out.write("\n")
    return count


class MarkdownRenderer:
    name = "markdown"

    def render(self, findings: Iterable[Finding], out: TextIO) -> int:
        return render_markdown(findings, out)
